### PR TITLE
feat: [TRST-913] Priority configuration for DataDog

### PR DESCRIPTION
**Pull request by timurhamitov**
Adding to Datadog the same high-priority configuration as Sentry has.

https://superdispatch.atlassian.net/browse/TRST-913

### CODE REVIEW

**Comment by timurhamitov** [comment]
@doniyor2109 What do you think: do we need this?

**Comment by doniyor2109** [comment]
@timurhamitov Yea, lets do it

**Comment by timurhamitov** [comment]
@doniyor2109 There is an error during the jest run. I'm trying to understand why it's happening

**Review by doniyor2109 — APPROVED** [review]

**Comment by timurhamitov** [comment]
@doniyor2109 It seems the error was inside the `source-map` package which is a jest dependency and related to the Nodejs version. Updated jest packages and some spec files. Is it ok?

**Comment by doniyor2109** [comment]
@timurhamitov Thanks. I like new snapshots. They are more readable.

**Pull request merged**
