### PR TITLE
feat(eslint-plugin): Add no-inline-condition rule

### PR DESCRIPTION
**Pull request by doniyor2109**

### CODE REVIEW

**Comment by umidbekkarimov** [comment]
@doniyor2109 eslint already have this rule

**Comment by doniyor2109** [comment]
@umidbekkarimov Really. Damn. Which rule is that?

**Comment by umidbekkarimov** [comment]
@doniyor2109 https://eslint.org/docs/rules/no-unused-expressions

**Comment by doniyor2109** [comment]
@umidbekkarimov Yes, I know this rule but it does not fixer and this rule checks for any `no-unused-expressions` like `foo;`

**Comment by umidbekkarimov** [comment]
@doniyor2109 it’s better to use codemod once, instead of trying to fix it with eslint every time. don’t forget eslint runs when you type, before commit and in ci, keep rules simple.
Also i’m sure there are tons of edge cases that you didn’t cover

**Pull request closed without merging**
